# Generated by Django 4.0.2 on 2022-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.BigIntegerField(unique=True)),
                ('mobile_no', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('clas', models.TextField(max_length=50)),
                ('dept', models.TextField(default='', max_length=50)),
                ('mentor', models.TextField(default='', max_length=50, null=True)),
                ('travel', models.IntegerField(default='')),
                ('cgpa', models.CharField(default='', max_length=10)),
                ('attendence', models.FloatField(default=0.0)),
                ('bloodgroup', models.CharField(default='O+', max_length=5)),
                ('language', models.TextField(default='', max_length=50)),
                ('internship', models.TextField(default='', max_length=50)),
                ('health', models.TextField(default='')),
                ('familymember', models.IntegerField(default=0)),
                ('annualin', models.BigIntegerField(default=0, null=True)),
                ('areaofinterest', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
