# Generated by Django 4.0.2 on 2022-03-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_profile_fatheroccupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='annualin',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
