# Generated by Django 4.0.2 on 2022-04-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_profile_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='clas',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='dept',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='algo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='dbms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='image',
            field=models.ImageField(default='', upload_to='student/images'),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='maths',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='micro',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='operating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='Roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
