# Generated by Django 4.0.2 on 2022-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_profile_clas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
